# Generated by Django 3.2.24 on 2024-04-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
    ]
