# Generated by Django 3.2.24 on 2024-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_score_userprofile_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='final_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
