# Generated by Django 3.2.24 on 2024-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glb_file', models.FileField(upload_to='glb_files/')),
            ],
        ),
    ]
