# Generated by Django 3.2.24 on 2024-02-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0003_auto_20240218_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
