# Generated by Django 3.2.24 on 2024-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0004_alter_collectable_glb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='glb_files/'),
        ),
    ]
