# Generated by Django 3.2.24 on 2024-03-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectables', '0005_alter_collectable_glb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectable',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
