# Generated by Django 3.2.24 on 2024-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='glb_image',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='glb_files/'),
        ),
    ]
