# Generated by Django 3.2.24 on 2024-03-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0002_auto_20240303_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='glb_file',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
    ]
