# Generated by Django 3.2.24 on 2024-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrades', '0003_auto_20240303_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='glb_files/'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
